name: Go Remote
on:
  push:
    branches: [main, master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v2
        
      - name: Checkout Test Scripts
        uses: actions/checkout@v2
        with:
          repository: lowkh/GoSchoolRemoteAccessExample
          path: testDirectory
          token: ${{ secrets.GO_REMOTE }}
      - name: Check files
        run: |
            cd testDirectory
            ls
            cat myText,txt
